# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `annex_29` gem.
# Please instead update this file by running `bin/tapioca gem annex_29`.

# source://annex_29//lib/annex_29.rb#1
module Annex29
  class << self
    # source://annex_29//lib/annex_29.rb#5
    def segment_words(input); end
  end
end

# source://annex_29//lib/annex_29/word_segmentation.rb#6
module Annex29::WordSegmentation
  class << self
    # source://annex_29//lib/annex_29/word_segmentation.rb#2809
    def call(input); end

    # Returns the value of attribute segmenter_en_main.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2801
    def segmenter_en_main; end

    # Sets the attribute segmenter_en_main
    #
    # @param value the value to set the attribute segmenter_en_main to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2801
    def segmenter_en_main=(_arg0); end

    # Returns the value of attribute segmenter_error.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2796
    def segmenter_error; end

    # Sets the attribute segmenter_error
    #
    # @param value the value to set the attribute segmenter_error to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2796
    def segmenter_error=(_arg0); end

    # Returns the value of attribute segmenter_first_final.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2792
    def segmenter_first_final; end

    # Sets the attribute segmenter_first_final
    #
    # @param value the value to set the attribute segmenter_first_final to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2792
    def segmenter_first_final=(_arg0); end

    # Returns the value of attribute segmenter_start.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2788
    def segmenter_start; end

    # Sets the attribute segmenter_start
    #
    # @param value the value to set the attribute segmenter_start to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2788
    def segmenter_start=(_arg0); end

    private

    # Returns the value of attribute _segmenter_eof_trans.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2779
    def _segmenter_eof_trans; end

    # Sets the attribute _segmenter_eof_trans
    #
    # @param value the value to set the attribute _segmenter_eof_trans to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2779
    def _segmenter_eof_trans=(_arg0); end

    # Returns the value of attribute _segmenter_from_state_actions.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2770
    def _segmenter_from_state_actions; end

    # Sets the attribute _segmenter_from_state_actions
    #
    # @param value the value to set the attribute _segmenter_from_state_actions to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2770
    def _segmenter_from_state_actions=(_arg0); end

    # Returns the value of attribute _segmenter_index_offsets.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1770
    def _segmenter_index_offsets; end

    # Sets the attribute _segmenter_index_offsets
    #
    # @param value the value to set the attribute _segmenter_index_offsets to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1770
    def _segmenter_index_offsets=(_arg0); end

    # Returns the value of attribute _segmenter_indicies.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1779
    def _segmenter_indicies; end

    # Sets the attribute _segmenter_indicies
    #
    # @param value the value to set the attribute _segmenter_indicies to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1779
    def _segmenter_indicies=(_arg0); end

    # Returns the value of attribute _segmenter_key_offsets.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#14
    def _segmenter_key_offsets; end

    # Sets the attribute _segmenter_key_offsets
    #
    # @param value the value to set the attribute _segmenter_key_offsets to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#14
    def _segmenter_key_offsets=(_arg0); end

    # Returns the value of attribute _segmenter_range_lengths.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1761
    def _segmenter_range_lengths; end

    # Sets the attribute _segmenter_range_lengths
    #
    # @param value the value to set the attribute _segmenter_range_lengths to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1761
    def _segmenter_range_lengths=(_arg0); end

    # Returns the value of attribute _segmenter_single_lengths.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1752
    def _segmenter_single_lengths; end

    # Sets the attribute _segmenter_single_lengths
    #
    # @param value the value to set the attribute _segmenter_single_lengths to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#1752
    def _segmenter_single_lengths=(_arg0); end

    # Returns the value of attribute _segmenter_to_state_actions.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2761
    def _segmenter_to_state_actions; end

    # Sets the attribute _segmenter_to_state_actions
    #
    # @param value the value to set the attribute _segmenter_to_state_actions to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2761
    def _segmenter_to_state_actions=(_arg0); end

    # Returns the value of attribute _segmenter_trans_actions.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2751
    def _segmenter_trans_actions; end

    # Sets the attribute _segmenter_trans_actions
    #
    # @param value the value to set the attribute _segmenter_trans_actions to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2751
    def _segmenter_trans_actions=(_arg0); end

    # Returns the value of attribute _segmenter_trans_keys.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#23
    def _segmenter_trans_keys; end

    # Sets the attribute _segmenter_trans_keys
    #
    # @param value the value to set the attribute _segmenter_trans_keys to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#23
    def _segmenter_trans_keys=(_arg0); end

    # Returns the value of attribute _segmenter_trans_targs.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2741
    def _segmenter_trans_targs; end

    # Sets the attribute _segmenter_trans_targs
    #
    # @param value the value to set the attribute _segmenter_trans_targs to.
    #
    # source://annex_29//lib/annex_29/word_segmentation.rb#2741
    def _segmenter_trans_targs=(_arg0); end
  end
end
