# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `trilogy` gem.
# Please instead update this file by running `bin/tapioca gem trilogy`.

class Errno::EAUTH < ::SystemCallError; end
Errno::EAUTH::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EBADARCH < ::SystemCallError; end
Errno::EBADARCH::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EBADEXEC < ::SystemCallError; end
Errno::EBADEXEC::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EBADMACHO < ::SystemCallError; end
Errno::EBADMACHO::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EBADRPC < ::SystemCallError; end
Errno::EBADRPC::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EDEVERR < ::SystemCallError; end
Errno::EDEVERR::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EFTYPE < ::SystemCallError; end
Errno::EFTYPE::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ELAST < ::SystemCallError; end
Errno::ELAST::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ENEEDAUTH < ::SystemCallError; end
Errno::ENEEDAUTH::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ENOATTR < ::SystemCallError; end
Errno::ENOATTR::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ENOPOLICY < ::SystemCallError; end
Errno::ENOPOLICY::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ENOTSUP < ::SystemCallError; end
Errno::ENOTSUP::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EPROCLIM < ::SystemCallError; end
Errno::EPROCLIM::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EPROCUNAVAIL < ::SystemCallError; end
Errno::EPROCUNAVAIL::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EPROGMISMATCH < ::SystemCallError; end
Errno::EPROGMISMATCH::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EPROGUNAVAIL < ::SystemCallError; end
Errno::EPROGUNAVAIL::Errno = T.let(T.unsafe(nil), Integer)
class Errno::EPWROFF < ::SystemCallError; end
Errno::EPWROFF::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ERPCMISMATCH < ::SystemCallError; end
Errno::ERPCMISMATCH::Errno = T.let(T.unsafe(nil), Integer)
class Errno::ESHLIBVERS < ::SystemCallError; end
Errno::ESHLIBVERS::Errno = T.let(T.unsafe(nil), Integer)

# source://trilogy//lib/trilogy/version.rb#1
class Trilogy
  # @return [Trilogy] a new instance of Trilogy
  #
  # source://trilogy//lib/trilogy.rb#10
  def initialize(options = T.unsafe(nil)); end

  def affected_rows; end
  def change_db(_arg0); end
  def close; end
  def closed?; end

  # source://trilogy//lib/trilogy.rb#39
  def connected_host; end

  # source://trilogy//lib/trilogy.rb#21
  def connection_options; end

  def discard!; end
  def escape(_arg0); end

  # @return [Boolean]
  #
  # source://trilogy//lib/trilogy.rb#25
  def in_transaction?; end

  def last_gtid; end
  def last_insert_id; end
  def more_results_exist?; end
  def next_result; end
  def ping; end
  def query(_arg0); end
  def query_flags; end
  def query_flags=(_arg0); end

  # source://trilogy//lib/trilogy.rb#43
  def query_with_flags(sql, flags); end

  def read_timeout; end
  def read_timeout=(_arg0); end
  def select_db(_arg0); end

  # source://trilogy//lib/trilogy.rb#29
  def server_info; end

  def server_status; end
  def server_version; end
  def set_server_option(_arg0); end
  def warning_count; end
  def write_timeout; end
  def write_timeout=(_arg0); end

  private

  def _connect(_arg0, _arg1, _arg2); end
end

# source://trilogy//lib/trilogy/error.rb#53
class Trilogy::BaseConnectionError < ::Trilogy::BaseError
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#43
class Trilogy::BaseError < ::StandardError
  include ::Trilogy::Error

  # @return [BaseError] a new instance of BaseError
  #
  # source://trilogy//lib/trilogy/error.rb#46
  def initialize(error_message = T.unsafe(nil), error_code = T.unsafe(nil)); end
end

Trilogy::CHARSET_ARMSCII8_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_ARMSCII8_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_ASCII_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_ASCII_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_BIG5_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_BIG5_CHINESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_BINARY = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1250_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1250_CROATIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1250_CZECH_CS = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1250_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1250_POLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1251_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1251_BULGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1251_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1251_GENERAL_CS = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1251_UKRAINIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1256_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1256_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1257_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1257_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP1257_LITHUANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP850_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP850_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP852_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP852_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP866_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP866_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP932_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_CP932_JAPANESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_DEC8_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_DEC8_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_EUCJPMS_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_EUCJPMS_JAPANESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_EUCKR_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_EUCKR_KOREAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GB18030_BIN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GB18030_CHINESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GB18030_UNICODE_520_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GB2312_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GB2312_CHINESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GBK_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GBK_CHINESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GEOSTD8_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GEOSTD8_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GREEK_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_GREEK_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_HEBREW_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_HEBREW_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_HP8_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_HP8_ENGLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_KEYBCS2_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_KEYBCS2_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_KOI8R_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_KOI8R_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_KOI8U_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_KOI8U_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_DANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_GENERAL_CS = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_GERMAN1_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_GERMAN2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_SPANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN1_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN2_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN2_CROATIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN2_CZECH_CS = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN2_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN2_HUNGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN5_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN5_TURKISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN7_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN7_ESTONIAN_CS = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN7_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_LATIN7_GENERAL_CS = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_MACCE_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_MACCE_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_MACROMAN_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_MACROMAN_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_NONE = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_SJIS_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_SJIS_JAPANESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_SWE7_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_SWE7_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_TIS620_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_TIS620_THAI_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_CZECH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_DANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_ESPERANTO_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_ESTONIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_GENERAL_MYSQL500_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_HUNGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_ICELANDIC_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_LATVIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_LITHUANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_PERSIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_POLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_ROMANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_ROMAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_SINHALA_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_SLOVAK_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_SLOVENIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_SPANISH2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_SPANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_TURKISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UCS2_UNICODE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UJIS_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UJIS_JAPANESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_CZECH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_DANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_ESPERANTO_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_ESTONIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_HUNGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_ICELANDIC_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_LATVIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_LITHUANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_PERSIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_POLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_ROMANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_ROMAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_SINHALA_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_SLOVAK_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_SLOVENIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_SPANISH2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_SPANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_TURKISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF16_UNICODE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_CZECH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_DANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_ESPERANTO_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_ESTONIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_HUNGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_ICELANDIC_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_LATVIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_LITHUANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_PERSIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_POLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_ROMANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_ROMAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_SINHALA_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_SLOVAK_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_SLOVENIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_SPANISH2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_SPANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_TURKISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF32_UNICODE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_0900_AI_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_CROATIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_CZECH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_DANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_ESPERANTO_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_ESTONIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_GERMAN2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_HUNGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_ICELANDIC_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_LATVIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_LITHUANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_PERSIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_POLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_ROMANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_ROMAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_SINHALA_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_SLOVAK_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_SLOVENIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_SPANISH2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_SPANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_TURKISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_UNICODE_520_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_UNICODE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8MB4_VIETNAMESE_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_BIN = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_CZECH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_DANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_ESPERANTO_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_ESTONIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_GENERAL_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_GENERAL_MYSQL500_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_HUNGARIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_ICELANDIC_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_LATVIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_LITHUANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_PERSIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_POLISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_ROMANIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_ROMAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_SINHALA_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_SLOVAK_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_SLOVENIAN_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_SPANISH2_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_SPANISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_SWEDISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_TURKISH_CI = T.let(T.unsafe(nil), Integer)
Trilogy::CHARSET_UTF8_UNICODE_CI = T.let(T.unsafe(nil), Integer)

# source://trilogy//lib/trilogy/error.rb#66
class Trilogy::CastError < ::Trilogy::ClientError; end

# Trilogy::ClientError is the base error type for invalid queries or parameters
# that shouldn't be retried.
#
# source://trilogy//lib/trilogy/error.rb#59
class Trilogy::ClientError < ::Trilogy::BaseError; end

# Raised on attempt to use connection which was explicitly closed by the user
#
# source://trilogy//lib/trilogy/error.rb#110
class Trilogy::ConnectionClosed < ::IOError
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# Trilogy::ConnectionError is the base error type for all potentially transient
# network errors.
#
# source://trilogy//lib/trilogy/error.rb#10
module Trilogy::ConnectionError
  include ::Trilogy::Error
end

# source://trilogy//lib/trilogy/error.rb#38
Trilogy::ConnectionRefusedError = Trilogy::SyscallError::ECONNREFUSED

# source://trilogy//lib/trilogy/error.rb#40
Trilogy::ConnectionResetError = Trilogy::SyscallError::ECONNRESET

# DatabaseError was replaced by ProtocolError, but we'll keep it around as an
# ancestor of ProtocolError for compatibility reasons (e.g. so `rescue DatabaseError`
# still works. We can remove this class in the next major release.
#
# source://trilogy//lib/trilogy/error.rb#75
module Trilogy::DatabaseError; end

# Occurs when a socket read or write returns EOF or when an operation is
# attempted on a socket which previously encountered an error.
#
# source://trilogy//lib/trilogy/error.rb#116
class Trilogy::EOFError < ::Trilogy::BaseConnectionError; end

# source://trilogy//lib/trilogy/encoding.rb#2
module Trilogy::Encoding
  class << self
    # source://trilogy//lib/trilogy/encoding.rb#93
    def charset(mysql_encoding); end

    # source://trilogy//lib/trilogy/encoding.rb#85
    def find(mysql_encoding); end
  end
end

# source://trilogy//lib/trilogy/encoding.rb#47
Trilogy::Encoding::CHARSETS = T.let(T.unsafe(nil), Hash)

# source://trilogy//lib/trilogy/encoding.rb#3
Trilogy::Encoding::RUBY_ENCODINGS = T.let(T.unsafe(nil), Hash)

# Trilogy::Error is the base error type. All errors raised by Trilogy
# should be descendants of Trilogy::Error
#
# source://trilogy//lib/trilogy/error.rb#4
module Trilogy::Error
  # Returns the value of attribute error_code.
  #
  # source://trilogy//lib/trilogy/error.rb#5
  def error_code; end
end

# source://trilogy//lib/trilogy/error.rb#78
class Trilogy::ProtocolError < ::Trilogy::BaseError
  include ::Trilogy::DatabaseError

  class << self
    # source://trilogy//lib/trilogy/error.rb#99
    def from_code(message, code); end
  end
end

# source://trilogy//lib/trilogy/error.rb#81
Trilogy::ProtocolError::ERROR_CODES = T.let(T.unsafe(nil), Hash)

Trilogy::QUERY_FLAGS_CAST = T.let(T.unsafe(nil), Integer)
Trilogy::QUERY_FLAGS_CAST_ALL_DECIMALS_TO_BIGDECIMALS = T.let(T.unsafe(nil), Integer)
Trilogy::QUERY_FLAGS_CAST_BOOLEANS = T.let(T.unsafe(nil), Integer)
Trilogy::QUERY_FLAGS_DEFAULT = T.let(T.unsafe(nil), Integer)
Trilogy::QUERY_FLAGS_FLATTEN_ROWS = T.let(T.unsafe(nil), Integer)
Trilogy::QUERY_FLAGS_LOCAL_TIMEZONE = T.let(T.unsafe(nil), Integer)
Trilogy::QUERY_FLAGS_NONE = T.let(T.unsafe(nil), Integer)

# source://trilogy//lib/trilogy/error.rb#63
class Trilogy::QueryError < ::Trilogy::ClientError; end

# source://trilogy//lib/trilogy/result.rb#2
class Trilogy::Result
  include ::Enumerable

  # Returns the value of attribute affected_rows.
  #
  # source://trilogy//lib/trilogy/result.rb#3
  def affected_rows; end

  # source://trilogy//lib/trilogy/result.rb#5
  def count; end

  # source://trilogy//lib/trilogy/result.rb#27
  def each(&bk); end

  # source://trilogy//lib/trilogy/result.rb#9
  def each_hash; end

  # Returns the value of attribute fields.
  #
  # source://trilogy//lib/trilogy/result.rb#3
  def fields; end

  # Returns the value of attribute last_insert_id.
  #
  # source://trilogy//lib/trilogy/result.rb#3
  def last_insert_id; end

  # Returns the value of attribute query_time.
  #
  # source://trilogy//lib/trilogy/result.rb#3
  def query_time; end

  # Returns the value of attribute rows.
  #
  # source://trilogy//lib/trilogy/result.rb#3
  def rows; end
end

Trilogy::SERVER_STATUS_AUTOCOMMIT = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_CURSOR_EXISTS = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_DB_DROPPED = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_IN_TRANS = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_LAST_ROW_SENT = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_METADATA_CHANGED = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_MORE_RESULTS_EXISTS = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_NO_BACKSLASH_ESCAPES = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_NO_GOOD_INDEX_USED = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_NO_INDEX_USED = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_PS_OUT_PARAMS = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_QUERY_WAS_SLOW = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_SESSION_STATE_CHANGED = T.let(T.unsafe(nil), Integer)
Trilogy::SERVER_STATUS_STATUS_IN_TRANS_READONLY = T.let(T.unsafe(nil), Integer)
Trilogy::SET_SERVER_MULTI_STATEMENTS_OFF = T.let(T.unsafe(nil), Integer)
Trilogy::SET_SERVER_MULTI_STATEMENTS_ON = T.let(T.unsafe(nil), Integer)

# source://trilogy//lib/trilogy/error.rb#105
class Trilogy::SSLError < ::Trilogy::BaseError
  include ::Trilogy::ConnectionError
end

Trilogy::SSL_DISABLED = T.let(T.unsafe(nil), Integer)
Trilogy::SSL_PREFERRED_NOVERIFY = T.let(T.unsafe(nil), Integer)
Trilogy::SSL_REQUIRED_NOVERIFY = T.let(T.unsafe(nil), Integer)
Trilogy::SSL_VERIFY_CA = T.let(T.unsafe(nil), Integer)
Trilogy::SSL_VERIFY_IDENTITY = T.let(T.unsafe(nil), Integer)

# Trilogy may raise various syscall errors, which we treat as Trilogy::Errors.
#
# source://trilogy//lib/trilogy/error.rb#15
module Trilogy::SyscallError
  class << self
    # source://trilogy//lib/trilogy/error.rb#32
    def from_errno(errno, message); end
  end
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::E2BIG < ::Errno::E2BIG
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EACCES < ::Errno::EACCES
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EADDRINUSE < ::Errno::EADDRINUSE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EADDRNOTAVAIL < ::Errno::EADDRNOTAVAIL
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EAFNOSUPPORT < ::Errno::EAFNOSUPPORT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EAGAIN < ::Errno::EAGAIN
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EALREADY < ::Errno::EALREADY
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EAUTH < ::Errno::EAUTH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBADARCH < ::Errno::EBADARCH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBADEXEC < ::Errno::EBADEXEC
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBADF < ::Errno::EBADF
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBADMACHO < ::Errno::EBADMACHO
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBADMSG < ::Errno::EBADMSG
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBADRPC < ::Errno::EBADRPC
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EBUSY < ::Errno::EBUSY
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ECANCELED < ::Errno::ECANCELED
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ECHILD < ::Errno::ECHILD
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ECONNABORTED < ::Errno::ECONNABORTED
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ECONNREFUSED < ::Errno::ECONNREFUSED
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ECONNRESET < ::Errno::ECONNRESET
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EDEADLK < ::Errno::EDEADLK
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EDESTADDRREQ < ::Errno::EDESTADDRREQ
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EDEVERR < ::Errno::EDEVERR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EDOM < ::Errno::EDOM
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EDQUOT < ::Errno::EDQUOT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EEXIST < ::Errno::EEXIST
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EFAULT < ::Errno::EFAULT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EFBIG < ::Errno::EFBIG
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EFTYPE < ::Errno::EFTYPE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EHOSTDOWN < ::Errno::EHOSTDOWN
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EHOSTUNREACH < ::Errno::EHOSTUNREACH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EIDRM < ::Errno::EIDRM
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EILSEQ < ::Errno::EILSEQ
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EINPROGRESS < ::Errno::EINPROGRESS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EINTR < ::Errno::EINTR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EINVAL < ::Errno::EINVAL
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EIO < ::Errno::EIO
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EISCONN < ::Errno::EISCONN
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EISDIR < ::Errno::EISDIR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ELAST < ::Errno::ELAST
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ELOOP < ::Errno::ELOOP
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EMFILE < ::Errno::EMFILE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EMLINK < ::Errno::EMLINK
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EMSGSIZE < ::Errno::EMSGSIZE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EMULTIHOP < ::Errno::EMULTIHOP
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENAMETOOLONG < ::Errno::ENAMETOOLONG
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENEEDAUTH < ::Errno::ENEEDAUTH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENETDOWN < ::Errno::ENETDOWN
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENETRESET < ::Errno::ENETRESET
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENETUNREACH < ::Errno::ENETUNREACH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENFILE < ::Errno::ENFILE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOATTR < ::Errno::ENOATTR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOBUFS < ::Errno::ENOBUFS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENODATA < ::Errno::ENODATA
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENODEV < ::Errno::ENODEV
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOENT < ::Errno::ENOENT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOEXEC < ::Errno::ENOEXEC
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOLCK < ::Errno::ENOLCK
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOLINK < ::Errno::ENOLINK
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOMEM < ::Errno::ENOMEM
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOMSG < ::Errno::ENOMSG
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOPOLICY < ::Errno::ENOPOLICY
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOPROTOOPT < ::Errno::ENOPROTOOPT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOSPC < ::Errno::ENOSPC
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOSR < ::Errno::ENOSR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOSTR < ::Errno::ENOSTR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOSYS < ::Errno::ENOSYS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTBLK < ::Errno::ENOTBLK
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTCONN < ::Errno::ENOTCONN
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTDIR < ::Errno::ENOTDIR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTEMPTY < ::Errno::ENOTEMPTY
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTRECOVERABLE < ::Errno::ENOTRECOVERABLE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTSOCK < ::Errno::ENOTSOCK
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTSUP < ::Errno::ENOTSUP
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENOTTY < ::Errno::ENOTTY
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ENXIO < ::Errno::ENXIO
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EOPNOTSUPP < ::Errno::EOPNOTSUPP
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EOVERFLOW < ::Errno::EOVERFLOW
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EOWNERDEAD < ::Errno::EOWNERDEAD
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPERM < ::Errno::EPERM
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPFNOSUPPORT < ::Errno::EPFNOSUPPORT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPIPE < ::Errno::EPIPE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROCLIM < ::Errno::EPROCLIM
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROCUNAVAIL < ::Errno::EPROCUNAVAIL
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROGMISMATCH < ::Errno::EPROGMISMATCH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROGUNAVAIL < ::Errno::EPROGUNAVAIL
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROTO < ::Errno::EPROTO
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROTONOSUPPORT < ::Errno::EPROTONOSUPPORT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPROTOTYPE < ::Errno::EPROTOTYPE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EPWROFF < ::Errno::EPWROFF
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ERANGE < ::Errno::ERANGE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EREMOTE < ::Errno::EREMOTE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EROFS < ::Errno::EROFS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ERPCMISMATCH < ::Errno::ERPCMISMATCH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#16
Trilogy::SyscallError::ERRORS = T.let(T.unsafe(nil), Hash)

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ESHLIBVERS < ::Errno::ESHLIBVERS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ESHUTDOWN < ::Errno::ESHUTDOWN
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ESOCKTNOSUPPORT < ::Errno::ESOCKTNOSUPPORT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ESPIPE < ::Errno::ESPIPE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ESRCH < ::Errno::ESRCH
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ESTALE < ::Errno::ESTALE
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ETIME < ::Errno::ETIME
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ETIMEDOUT < ::Errno::ETIMEDOUT
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ETOOMANYREFS < ::Errno::ETOOMANYREFS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::ETXTBSY < ::Errno::ETXTBSY
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EUSERS < ::Errno::EUSERS
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::EXDEV < ::Errno::EXDEV
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

# source://trilogy//lib/trilogy/error.rb#23
class Trilogy::SyscallError::NOERROR < ::Errno::NOERROR
  include ::Trilogy::Error
  include ::Trilogy::ConnectionError
end

Trilogy::TLS_VERSION_10 = T.let(T.unsafe(nil), Integer)
Trilogy::TLS_VERSION_11 = T.let(T.unsafe(nil), Integer)
Trilogy::TLS_VERSION_12 = T.let(T.unsafe(nil), Integer)
Trilogy::TLS_VERSION_13 = T.let(T.unsafe(nil), Integer)

# source://trilogy//lib/trilogy/error.rb#69
class Trilogy::TimeoutError < ::Trilogy::BaseConnectionError; end

# source://trilogy//lib/trilogy/version.rb#2
Trilogy::VERSION = T.let(T.unsafe(nil), String)
