# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AtlasEngine::AddressValidation::PredicatePipeline`.
# Please instead update this file by running `bin/tapioca dsl AtlasEngine::AddressValidation::PredicatePipeline`.

class AtlasEngine::AddressValidation::PredicatePipeline
  include FrozenRecordAttributeMethods

  module FrozenRecordAttributeMethods
    sig { returns(T.untyped) }
    def full_address_validator; end

    sig { returns(T::Boolean) }
    def full_address_validator?; end

    sig { returns(T.untyped) }
    def id; end

    sig { returns(T::Boolean) }
    def id?; end

    sig { returns(T.untyped) }
    def pipeline; end

    sig { returns(T::Boolean) }
    def pipeline?; end
  end
end
